from .degree import DegreeService
from .university import UniversityService
from .document_type import DocumentTypeService
from .department import DepartmentService
from .student import StudentService
from .specialty_type import SpecialtyTypeService
from .dedication_type import DedicationTypeService
from .area import AreaService
from .specialty import SpecialtyService
from .plan import PlanService
from .subject import SubjectService
from .position_category import PositionCategoryService
from .group import GroupService
from .position import PositionService
from .orientation import OrientationService
from .authority import AuthorityService
from .faculty import FacultyService
