from .university import UniversitySerializer
from .area import AreaSerializer
from .document_type import DocumentTypeSerializer
from .dedication_type import DedicationTypeSerializer
from .position_category import PositionCategorySerializer
from .group import GroupSerializer
from .degree import DegreeSerializer
from .department import DepartmentSerializer
from .specialty_type import SpecialtyTypeSerializer
from .plan import PlanSerializer
from .position import PositionSerializer
from .student import StudentSerializer
from .authority import AuthoritySerializer
from .faculty import FacultySerializer
from .specialty import SpecialtySerializer
from .subject import SubjectSerializer
from .orientation import OrientationSerializer
