from .degree import Degree
from .university import University
from .document_type import DocumentType
from .department import Department
from .student import Student
from .specialty_type import SpecialtyType
from .dedication_type import DedicationType
from .area import Area
from .specialty import Specialty
from .plan import Plan
from .subject import Subject
from .position_category import PositionCategory
from .group import Group
from .position import Position
from .orientation import Orientation
from .authority import Authority
from .faculty import Faculty
