from .degree import DegreeRepository
from .university import UniversityRepository
from .document_type import DocumentTypeRepository
from .department import DepartmentRepository
from .student import StudentRepository
from .specialty_type import SpecialtyTypeRepository
from .dedication_type import DedicationTypeRepository
from .area import AreaRepository
from .specialty import SpecialtyRepository
from .plan import PlanRepository
from .subject import SubjectRepository
from .position_category import PositionCategoryRepository
from .group import GroupRepository
from .position import PositionRepository
from .orientation import OrientationRepository
from .authority import AuthorityRepository
from .faculty import FacultyRepository
