from .degree_repository import DegreeRepository
from .university_repository import UniversityRepository
from .document_type_repository import DocumentTypeRepository
from .department_repository import DepartmentRepository
from .student_repository import StudentRepository
from .specialty_type_repository import SpecialtyTypeRepository
from .dedication_type_repository import DedicationTypeRepository
from .area_repository import AreaRepository
from .specialty_repository import SpecialtyRepository
from .plan_repository import PlanRepository
from .subject_repository import SubjectRepository
from .position_category_repository import PositionCategoryRepository
from .group_repository import GroupRepository
from .position_repository import PositionRepository
from .orientation_repository import OrientationRepository
from .authority_repository import AuthorityRepository
from .faculty_repository import FacultyRepository

